//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class desacriptaion
    {
        public desacriptaion()
        {
            this.exam_q = new HashSet<exam_q>();
            this.exam_q1 = new HashSet<exam_q>();
            this.exam_q2 = new HashSet<exam_q>();
            this.exam_q3 = new HashSet<exam_q>();
            this.exam_q_levels = new HashSet<exam_q_levels>();
            this.exam_q_levels1 = new HashSet<exam_q_levels>();
            this.exam_q_levels2 = new HashSet<exam_q_levels>();
            this.exam_q_levels3 = new HashSet<exam_q_levels>();
            this.RespTrainShorts = new HashSet<RespTrainShort>();
        }
    
        public int id { get; set; }
        public string desacriptaion1 { get; set; }
    
        public virtual ICollection<exam_q> exam_q { get; set; }
        public virtual ICollection<exam_q> exam_q1 { get; set; }
        public virtual ICollection<exam_q> exam_q2 { get; set; }
        public virtual ICollection<exam_q> exam_q3 { get; set; }
        public virtual ICollection<exam_q_levels> exam_q_levels { get; set; }
        public virtual ICollection<exam_q_levels> exam_q_levels1 { get; set; }
        public virtual ICollection<exam_q_levels> exam_q_levels2 { get; set; }
        public virtual ICollection<exam_q_levels> exam_q_levels3 { get; set; }
        public virtual ICollection<RespTrainShort> RespTrainShorts { get; set; }
    }
}
