//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class examWithLevel
    {
        public int num_exam { get; set; }
        public Nullable<int> max_num_question { get; set; }
        public string level { get; set; }
        public string stage { get; set; }
        public int user_ID { get; set; }
    }
}
