//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedBackWithDetail
    {
        public int user_ID { get; set; }
        public System.DateTime datetime { get; set; }
        public string email { get; set; }
        public Nullable<bool> blind { get; set; }
        public Nullable<bool> mailList { get; set; }
        public string question { get; set; }
        public string suggetion { get; set; }
        public string free_text { get; set; }
        public string blind_details { get; set; }
    
        public virtual userID userID { get; set; }
    }
}
