//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class level_4
    {
        public int user_ID { get; set; }
        public System.DateTime datetime { get; set; }
        public Nullable<int> numsuccess { get; set; }
        public Nullable<int> level_unity { get; set; }
        public Nullable<int> x1 { get; set; }
        public Nullable<int> y1 { get; set; }
        public Nullable<int> x2 { get; set; }
        public Nullable<int> y2 { get; set; }
        public Nullable<int> x3 { get; set; }
        public Nullable<int> y3 { get; set; }
        public Nullable<int> frame { get; set; }
        public Nullable<int> num_collision { get; set; }
    
        public virtual userID userID { get; set; }
    }
}
