//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class level_2
    {
        public int user_ID { get; set; }
        public Nullable<int> Frame { get; set; }
        public Nullable<int> X1 { get; set; }
        public Nullable<int> Y1 { get; set; }
        public string color1 { get; set; }
        public string shape1 { get; set; }
        public Nullable<int> X2 { get; set; }
        public Nullable<int> Y2 { get; set; }
        public string color2 { get; set; }
        public string shape2 { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual userID userID { get; set; }
    }
}
