//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class level_1
    {
        public int user_ID { get; set; }
        public Nullable<int> feame { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public string Color { get; set; }
        public string shape { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual userID userID { get; set; }
    }
}
