//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxUserStepByStep
    {
        public int user_ID { get; set; }
        public int id { get; set; }
        public System.DateTime Time { get; set; }
        public int duration { get; set; }
        public Nullable<bool> right { get; set; }
    }
}
