//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class parmater
    {
        public int user_ID { get; set; }
        public System.DateTime datetime { get; set; }
        public string filter { get; set; }
        public string cue_type { get; set; }
        public Nullable<int> cue_Volume_10 { get; set; }
        public Nullable<int> speed { get; set; }
    
        public virtual userID userID { get; set; }
    }
}
