//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pic_paths
    {
        public pic_paths()
        {
            this.exam_q = new HashSet<exam_q>();
            this.exam_q_levels = new HashSet<exam_q_levels>();
        }
    
        public int id { get; set; }
        public string pic_path { get; set; }
    
        public virtual ICollection<exam_q> exam_q { get; set; }
        public virtual ICollection<exam_q_levels> exam_q_levels { get; set; }
    }
}
