//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespTrainShort
    {
        public int user_ID { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> stage { get; set; }
        public Nullable<int> desacriptaion { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual desacriptaion desacriptaion1 { get; set; }
        public virtual level level1 { get; set; }
        public virtual stage stage1 { get; set; }
        public virtual userID userID { get; set; }
    }
}
