//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespTrain
    {
        public int user_ID { get; set; }
        public string classes { get; set; }
        public string stage { get; set; }
        public string number { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual userID userID { get; set; }
    }
}
