//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class resualt_exam_row
    {
        public Nullable<long> row_num { get; set; }
        public int user_ID { get; set; }
        public Nullable<int> num_exam { get; set; }
        public string stage { get; set; }
        public string level { get; set; }
        public Nullable<int> num_correct { get; set; }
    }
}
