//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class shadow
    {
        public int user_ID { get; set; }
        public int level { get; set; }
        public Nullable<int> freame { get; set; }
        public Nullable<int> success { get; set; }
        public string direction { get; set; }
        public Nullable<double> line { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual userID userID { get; set; }
    }
}
