//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShelonFinish
    {
        public int user_id { get; set; }
        public Nullable<bool> musical { get; set; }
        public Nullable<bool> playMusic { get; set; }
        public string namePlay { get; set; }
        public string numYear { get; set; }
        public Nullable<int> complex { get; set; }
        public Nullable<int> fun { get; set; }
        public Nullable<int> letters { get; set; }
        public Nullable<int> faces { get; set; }
        public Nullable<int> camera { get; set; }
        public string hard { get; set; }
        public string easy { get; set; }
        public Nullable<bool> pictureInstead { get; set; }
        public Nullable<bool> descInstead { get; set; }
        public Nullable<bool> closeEyes { get; set; }
        public int clearColor { get; set; }
        public int HardColor { get; set; }
        public string freeText { get; set; }
    
        public virtual userID userID { get; set; }
    }
}
