//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class stage
    {
        public stage()
        {
            this.exams = new HashSet<exam>();
            this.exam_q_levels = new HashSet<exam_q_levels>();
            this.RespTrainShorts = new HashSet<RespTrainShort>();
        }
    
        public int id { get; set; }
        public string stage1 { get; set; }
    
        public virtual ICollection<exam> exams { get; set; }
        public virtual ICollection<exam_q_levels> exam_q_levels { get; set; }
        public virtual ICollection<RespTrainShort> RespTrainShorts { get; set; }
    }
}
