//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class stepbystepMin
    {
        public int idSub { get; set; }
        public Nullable<System.DateTime> minTime { get; set; }
        public int subUser { get; set; }
        public int userName { get; set; }
    }
}
