//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class step_by_step
    {
        public int id { get; set; }
        public string correct { get; set; }
        public string title { get; set; }
        public int pic_path { get; set; }
        public int types { get; set; }
    }
}
