//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sumShachar
    {
        public int id { get; set; }
        public int frame { get; set; }
        public int success { get; set; }
        public int timeout { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public int z { get; set; }
        public int angle { get; set; }
        public int distance { get; set; }
        public string level { get; set; }
        public string experiment_name { get; set; }
    }
}
