//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyemusic45.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class userID
    {
        public userID()
        {
            this.exams = new HashSet<exam>();
            this.exams1 = new HashSet<exam>();
            this.exams2 = new HashSet<exam>();
            this.feedBackWithDetails = new HashSet<feedBackWithDetail>();
            this.level_1 = new HashSet<level_1>();
            this.level_2 = new HashSet<level_2>();
            this.level_3 = new HashSet<level_3>();
            this.level_4 = new HashSet<level_4>();
            this.level_5 = new HashSet<level_5>();
            this.level_6 = new HashSet<level_6>();
            this.parmaters = new HashSet<parmater>();
            this.RespTrainShorts = new HashSet<RespTrainShort>();
            this.shadows = new HashSet<shadow>();
            this.StepByStepHappies = new HashSet<StepByStepHappy>();
            this.virtualGames = new HashSet<virtualGame>();
            this.RespTrains = new HashSet<RespTrain>();
            this.stepByStep_user = new HashSet<stepByStep_user>();
        }
    
        public int user_ID { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string level_blind { get; set; }
        public Nullable<int> birth_year { get; set; }
        public string gander { get; set; }
        public Nullable<int> age_of_blind { get; set; }
        public string place { get; set; }
        public string yourself { get; set; }
        public Nullable<int> precent_blind { get; set; }
        public bool fill_somting { get; set; }
        public Nullable<int> previos_expirments_num { get; set; }
        public Nullable<int> speed { get; set; }
        public Nullable<int> cue_Volume { get; set; }
        public string cue_type { get; set; }
        public string filter { get; set; }
        public string len { get; set; }
        public string rule { get; set; }
    
        public virtual ICollection<exam> exams { get; set; }
        public virtual ICollection<exam> exams1 { get; set; }
        public virtual ICollection<exam> exams2 { get; set; }
        public virtual ICollection<feedBackWithDetail> feedBackWithDetails { get; set; }
        public virtual ICollection<level_1> level_1 { get; set; }
        public virtual ICollection<level_2> level_2 { get; set; }
        public virtual ICollection<level_3> level_3 { get; set; }
        public virtual ICollection<level_4> level_4 { get; set; }
        public virtual ICollection<level_5> level_5 { get; set; }
        public virtual ICollection<level_6> level_6 { get; set; }
        public virtual ICollection<parmater> parmaters { get; set; }
        public virtual ICollection<RespTrainShort> RespTrainShorts { get; set; }
        public virtual ICollection<shadow> shadows { get; set; }
        public virtual ShelonFinish ShelonFinish { get; set; }
        public virtual ICollection<StepByStepHappy> StepByStepHappies { get; set; }
        public virtual ICollection<virtualGame> virtualGames { get; set; }
        public virtual ICollection<RespTrain> RespTrains { get; set; }
        public virtual ICollection<stepByStep_user> stepByStep_user { get; set; }
    }
}
